histour-bootstrap/src/main/java/trible/histour/bootstrap/secret/SecretProcessor.java, histour-bootstrap/src/main/resources/META-INF/spring.factories, histour-bootstrap/src/main/resources/application-local.yml, histour-bootstrap/src/main/resources/application-prod.yml, histour-output-postgresql/src/main/resources/database-config/application-local.yml, histour-output-postgresql/src/main/resources/database-config/application-prod.yml
closed #10 
- 시크릿 매니저를 도입했습니다.
- 오픈소스 [infisical](https://infisical.com/)을 활용했습니다. 주변에서 활용 및 추천받아 히스투어 프로젝트에서도 적용해보았습니다.
- 인텔리제이 환경변수 추가 설정이 필요하니 꼭 진행해주세요.
- [인텔리제이 환경변수 설정](https://devlog-wjdrbs96.tistory.com/363) : 이전에 참고했던 아티클 공유드립니다~
```
SECRET_MANAGER_TOKEN = {TOKEN}
SECRET_MANAGER_WORKSPACE_ID = {WORKSPACE_ID}
```
- 토큰/ID 값은 노션에서 공유드리겠습니다. 계정 관련 페이지 참고해주세요.
- 이 외 추가설명은 정기 회의 중 공유드리도록 하겠습니다! 궁금한 점이 있다면 편하게 질문주세요 :)
=> add: Secret Manager 도입

build.gradle, histour-application/build.gradle, histour-application/src/main/java/trible/histour/application/domain/auth/AuthService.java, histour-application/src/main/java/trible/histour/application/domain/auth/HistourAuthentication.java, histour-application/src/main/java/trible/histour/application/domain/auth/SecretKeyFactory.java, histour-application/src/main/java/trible/histour/application/domain/auth/TokenManager.java, histour-application/src/main/java/trible/histour/application/domain/member/Member.java, histour-application/src/main/resources/application-config/application-local.yml, histour-application/src/main/resources/application-config/application-prod.yml, histour-application/src/test/java/trible/histour/application/TokenManagerTest.java, histour-bootstrap/src/main/resources/application-local.yml, histour-bootstrap/src/main/resources/application-prod.yml, histour-common/src/main/java/trible/histour/common/exception/ExceptionCode.java, histour-input-http/build.gradle, histour-input-http/src/main/java/trible/histour/input/http/config/SecurityConfig.java, histour-input-http/src/main/java/trible/histour/input/http/controller/TestApi.java, histour-input-http/src/main/java/trible/histour/input/http/controller/docs/TestApiDocs.java, histour-input-http/src/main/java/trible/histour/input/http/controller/dto/response/ExceptionResponse.java, histour-input-http/src/main/java/trible/histour/input/http/docs/TestApiDocs.java, histour-input-http/src/main/java/trible/histour/input/http/web/HistourAuthenticationEntryPoint.java, histour-input-http/src/main/java/trible/histour/input/http/web/HistourAuthenticationFilter.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/MemberEntity.java
closed #8 
- Security 관련 로직을 추가했습니다.
- 토큰(JWT) 발급/검증 기능을 구현했습니다.
- 토큰을 검증하는 Filter 및 SecurityConfig 클래스를 구현했습니다.
=> feat: Security 기능 구현

histour-bootstrap/build.gradle, histour-bootstrap/src/main/java/trible/histour/bootstrap/secret/SecretProcessor.java, histour-common/src/main/java/trible/histour/common/exception/ExceptionCode.java, histour-common/src/main/java/trible/histour/common/exception/HisTourException.java, histour-common/src/main/java/trible/histour/common/exception/HistourException.java, histour-input-http/src/main/java/trible/histour/input/http/controller/dto/response/ExceptionResponse.java, histour-input-http/src/main/java/trible/histour/input/http/web/ExceptionAdvice.java, histour-input-http/src/main/java/trible/histour/input/http/web/HistourAuthenticationEntryPoint.java, histour-output-postgresql/build.gradle, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/converter/MissionTypeListConverter.java
closed #17 
branch 이슈로 PR이 자동으로 닫혀 재PR 올립니다!
히스투어용 예외를 커스텀했습니다.
예외를 처리하기 위한 ExceptionAdvice를 추가했습니다.
=> add: custom exception

histour-application/build.gradle, histour-application/src/main/java/trible/histour/application/domain/character/Character.java, histour-application/src/main/java/trible/histour/application/domain/character/CharacterService.java, histour-application/src/main/java/trible/histour/application/domain/character/CharacterType.java, histour-application/src/main/java/trible/histour/application/port/input/CharacterUseCase.java, histour-application/src/main/java/trible/histour/application/port/input/dto/response/CharactersResponse.java, histour-application/src/main/java/trible/histour/application/port/output/persistence/CharacterPort.java, histour-input-http/build.gradle, histour-input-http/src/main/java/trible/histour/input/http/config/SecurityConfig.java, histour-input-http/src/main/java/trible/histour/input/http/controller/CharacterApi.java, histour-input-http/src/main/java/trible/histour/input/http/controller/docs/CharacterApiDocs.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/adapter/CharacterAdapter.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/CharacterEntity.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/repository/CharacterRepository.java
=> feature: 캐릭터 전체 조회 api

.github/workflows/cd.yml
closed #32 
* cd스크립트에서 도커파일-prod를 실행하도록 수정했습니다.
=> fix : cd script with dockerfile

Dockerfile-prod
closed #34
dockerfile에 있는 jar이름을 수정했습니다.
=> fix dockerfile-prod script

Dockerfile-prod
closed #36
* dockerfile에 jar파일 이름에 문제가 있어 이를 수정했습니다.
=> fix : dockerfile script jar name

build.gradle
closed #40 
* build.gradle의 경로를 수정했습니다.
=> fix : build.gradle manifest path

build.gradle
closed #42
*  'Main-Class': 'trible.histour.bootstrap.HistourBootstrapApplication.java' 에서 .java를 제거했습니다.
=> fix : build.gradle manifest file name

Dockerfile-prod, build.gradle
closed #46 
* cd로직을 수정했습니다.
* jar와 bootjar의 차이에 대해서 알게되었어요. 참고 자료입니다!
* https://dongjuppp.tistory.com/87
=> fix : cd logic

Dockerfile-prod, build.gradle
closed #48
* dockerfile에서 복사하는 jar파일 종류를 수정했습니다.
=> fix : build.gradle Dockerfile

Dockerfile-prod
closed #50
* dockerfile의 jar파일 경로를 수정했습니다.
=> fix : Dockerfile jar path

histour-application/src/main/java/trible/histour/application/domain/mission/MemberMission.java, histour-application/src/main/java/trible/histour/application/domain/mission/MissionService.java, histour-application/src/main/java/trible/histour/application/port/input/MissionUseCase.java, histour-application/src/main/java/trible/histour/application/port/input/dto/response/mission/MissionResponse.java, histour-application/src/main/java/trible/histour/application/port/input/dto/response/mission/MissionsResponse.java, histour-application/src/main/java/trible/histour/application/port/output/persistence/QuizPort.java, histour-input-http/src/main/java/trible/histour/input/http/controller/MissionApi.java, histour-input-http/src/main/java/trible/histour/input/http/controller/docs/MissionApiDocs.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/adapter/QuizAdapter.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/MemberMissionEntity.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/repository/QuizRepository.java
closed #62 
- 미션 지도 뷰에서 활용하는 api 구현
=> feature: 미션 목록 조회 api

histour-application/src/main/java/trible/histour/application/domain/mission/MemberMission.java, histour-application/src/main/java/trible/histour/application/domain/mission/MissionService.java, histour-application/src/main/java/trible/histour/application/domain/place/PlaceService.java, histour-application/src/main/java/trible/histour/application/port/input/MissionUseCase.java, histour-application/src/main/java/trible/histour/application/port/input/PlaceUseCase.java, histour-application/src/main/java/trible/histour/application/port/input/dto/response/mission/MissionResponse.java, histour-application/src/main/java/trible/histour/application/port/input/dto/response/mission/MissionsResponse.java, histour-application/src/main/java/trible/histour/application/port/input/dto/response/place/PlaceResponse.java, histour-application/src/main/java/trible/histour/application/port/input/dto/response/place/PlacesResponse.java, histour-application/src/main/java/trible/histour/application/port/output/persistence/MemberMissionPort.java, histour-application/src/main/java/trible/histour/application/port/output/persistence/MissionPort.java, histour-application/src/main/java/trible/histour/application/port/output/persistence/PlacePort.java, histour-application/src/main/java/trible/histour/application/port/output/persistence/QuizPort.java, histour-input-http/src/main/java/trible/histour/input/http/controller/MissionApi.java, histour-input-http/src/main/java/trible/histour/input/http/controller/PlaceApi.java, histour-input-http/src/main/java/trible/histour/input/http/controller/docs/MissionApiDocs.java, histour-input-http/src/main/java/trible/histour/input/http/controller/docs/PlaceApiDocs.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/adapter/MemberMissionAdapter.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/adapter/MissionAdapter.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/adapter/PlaceAdapter.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/adapter/QuizAdapter.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/MemberMissionEntity.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/repository/MemberMissionRepository.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/repository/MissionRepository.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/repository/QuizRepository.java
closed #60 
- api 추가
- 전체 미션 개수 기준에 대한 논의가 추가로 필요합니다. (논의 완료)
=> feature: 여행지 목록 조회 api

histour-application/src/main/java/trible/histour/application/domain/auth/AuthService.java, histour-application/src/main/java/trible/histour/application/port/input/AuthUseCase.java, histour-application/src/main/java/trible/histour/application/port/output/persistence/MemberPort.java, histour-input-http/src/main/java/trible/histour/input/http/controller/AuthApi.java, histour-input-http/src/main/java/trible/histour/input/http/controller/docs/AuthApiDocs.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/adapter/MemberAdapter.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/repository/MemberMissionRepository.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/repository/MemberQuizRepository.java
closed #68 
closed #69 
closed #70 
- api 추가
- 액세스 토큰 재발급
- 로그아웃
- 회원탈퇴
- 소셜로그인 API가 Swagger 실행되지 않는 문제를 해결했습니다.
=> feature: 인증 관련 API

histour-application/src/main/java/trible/histour/application/domain/character/Character.java, histour-application/src/main/java/trible/histour/application/domain/character/CharacterColorInfo.java, histour-application/src/main/java/trible/histour/application/domain/character/CharacterCommentInfo.java, histour-application/src/main/java/trible/histour/application/domain/character/CharacterImageInfo.java, histour-application/src/main/java/trible/histour/application/port/input/dto/response/character/CharacterColorResponse.java, histour-application/src/main/java/trible/histour/application/port/input/dto/response/character/CharacterCommentResponse.java, histour-application/src/main/java/trible/histour/application/port/input/dto/response/character/CharacterImageResponse.java, histour-application/src/main/java/trible/histour/application/port/input/dto/response/character/CharacterResponse.java, histour-application/src/main/java/trible/histour/application/port/input/dto/response/character/CharactersResponse.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/CharacterEntity.java
=> fix: 캐릭터 테이블 수정

histour-application/src/main/java/trible/histour/application/domain/member/MemberService.java, histour-application/src/main/java/trible/histour/application/port/input/MemberUseCase.java, histour-application/src/main/java/trible/histour/application/port/input/dto/response/member/MemberInfoResponse.java, histour-application/src/main/java/trible/histour/application/port/output/persistence/CharacterPort.java, histour-input-http/src/main/java/trible/histour/input/http/controller/MemberApi.java, histour-input-http/src/main/java/trible/histour/input/http/controller/docs/MemberApiDocs.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/adapter/CharacterAdapter.java, histour-output-postgresql/src/main/resources/database-config/application-local.yml
closed #61 
* 회원 정보를 조회하는 api추가
=> feature : 회원 정보 조회 API

histour-application/src/main/java/trible/histour/application/domain/mission/Mission.java, histour-application/src/main/java/trible/histour/application/domain/quiz/QuizType.java, histour-application/src/main/java/trible/histour/application/port/input/dto/response/mission/MissionResponse.java, histour-input-http/src/main/java/trible/histour/input/http/controller/docs/AttractionApiDocs.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/MissionEntity.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/PlaceEntity.java
=> add: 추가 필요 값 추가

histour-application/src/main/java/trible/histour/application/domain/mission/MemberMission.java, histour-application/src/main/java/trible/histour/application/domain/mission/MissionService.java, histour-application/src/main/java/trible/histour/application/port/input/MissionUseCase.java, histour-application/src/main/java/trible/histour/application/port/output/persistence/MemberMissionPort.java, histour-input-http/src/main/java/trible/histour/input/http/controller/MissionApi.java, histour-input-http/src/main/java/trible/histour/input/http/controller/docs/MissionApiDocs.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/adapter/MemberMissionAdapter.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/MemberMissionEntity.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/repository/MemberMissionRepository.java
=> feature: 미션 해금 api

histour-application/src/main/java/trible/histour/application/domain/place/Place.java, histour-application/src/main/java/trible/histour/application/port/input/dto/response/place/PlaceResponse.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/PlaceEntity.java
closed #none
- 장소별 서브미션 고르는 이미지 url 필드 추가
=> add: 장소별 서브미션 고르는 이미지 url 필드 추가

histour-application/src/main/java/trible/histour/application/port/input/dto/response/character/CharacterResponse.java
=> fix: 스웨거 설명 수정

histour-application/src/main/java/trible/histour/application/domain/character/CharacterImageInfo.java, histour-application/src/main/java/trible/histour/application/port/input/dto/response/character/CharacterImageResponse.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/entity/CharacterEntity.java
closed #89 
- 캐릭터 얼굴 이미지 url 추가
=> add: 캐릭터 얼굴 이미지 칼럼 추가

histour-application/src/main/java/trible/histour/application/domain/place/PlaceService.java, histour-application/src/main/java/trible/histour/application/port/input/PlaceUseCase.java, histour-application/src/main/java/trible/histour/application/port/input/dto/request/place/PlaceRecommendRequest.java, histour-common/src/main/java/trible/histour/common/logger/HookLogger.java, histour-common/src/main/java/trible/histour/common/logger/discord/DiscordWebhookLogger.java, histour-common/src/main/java/trible/histour/common/logger/dto/request/DiscordRequest.java, histour-common/src/main/resources/discord-config/application-local.yml, histour-common/src/main/resources/discord-config/application-prod.yml, histour-common/src/test/java/trible/histour/common/logger/discord/DiscordWebhookLoggerTest.java, histour-input-http/src/main/java/trible/histour/input/http/controller/PlaceApi.java, histour-input-http/src/main/java/trible/histour/input/http/controller/docs/PlaceApiDocs.java, histour-input-http/src/main/java/trible/histour/input/http/web/ExceptionAdvice.java
closed #94 
- 여행지 추천 API 추가 개발
=> feat: recommend place API

histour-application/src/main/java/trible/histour/application/domain/attraction/AttractionService.java, histour-application/src/main/java/trible/histour/application/domain/quiz/MemberQuiz.java, histour-application/src/main/java/trible/histour/application/domain/quiz/QuizService.java, histour-application/src/main/java/trible/histour/application/port/input/QuizUseCase.java, histour-application/src/main/java/trible/histour/application/port/input/dto/request/quiz/QuizGradeRequest.java, histour-application/src/main/java/trible/histour/application/port/input/dto/response/quiz/QuizGradeResponse.java, histour-application/src/main/java/trible/histour/application/port/output/persistence/MemberMissionPort.java, histour-application/src/main/java/trible/histour/application/port/output/persistence/MemberQuizPort.java, histour-application/src/main/java/trible/histour/application/port/output/persistence/QuizPort.java, histour-input-http/src/main/java/trible/histour/input/http/controller/QuizApi.java, histour-input-http/src/main/java/trible/histour/input/http/controller/docs/MemberApiDocs.java, histour-input-http/src/main/java/trible/histour/input/http/controller/docs/QuizApiDocs.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/adapter/MemberMissionAdapter.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/adapter/MemberQuizAdapter.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/adapter/QuizAdapter.java, histour-output-postgresql/src/main/java/trible/histour/output/postgresql/persistence/repository/MemberMissionRepository.java
closed #66
* 사용자의 답변을 채점하는 API입니다.
=> feature: 퀴즈 채점 API

histour-application/src/main/java/trible/histour/application/port/input/dto/response/mission/MissionsResponse.java
closed #99 
- 이미지 url 필드를 추가합니다.
=> add: 미션 선택 이미지 필드 추가

histour-input-http/src/main/java/trible/histour/input/http/web/ExceptionAdvice.java
closed #103 
- 잘못된 포맷 형식이 들어올 경우 400 예외로 던집니다.
=> feat: 예외 핸들러 추가

histour-application/src/main/java/trible/histour/application/domain/auth/AuthService.java, histour-application/src/main/resources/application-config/application-local.yml, histour-application/src/main/resources/application-config/application-prod.yml
closed #106 
- 토큰 만료 시간 값을 설정 파일로 이동했습니다.
=> fix: 토큰 만료 시간 위치 이동

histour-application/src/main/java/trible/histour/application/domain/member/Member.java, histour-application/src/main/java/trible/histour/application/port/input/dto/response/member/MemberInfoResponse.java, histour-output-web/oauth/src/main/java/trible/histour/output/web/oauth/adapter/AppleService.java
closed #108 
- 투두 삭제
- profileImageUrl 필드 삭제
=> delete: 미사용 코드 삭제

histour-application/src/main/java/trible/histour/application/domain/assistant/AssistantService.java, histour-application/src/main/java/trible/histour/application/port/input/AssistantUseCase.java, histour-application/src/main/java/trible/histour/application/port/input/dto/request/assistant/ChatAssistantRequest.java, histour-application/src/main/java/trible/histour/application/port/input/dto/response/assistant/ChatAssistantResponse.java, histour-application/src/main/java/trible/histour/application/port/output/web/DataPort.java, histour-application/src/main/java/trible/histour/application/port/output/web/dto/request/ChatAssistantAiRequest.java, histour-application/src/main/java/trible/histour/application/port/output/web/dto/response/ChatAssistantAiResponse.java, histour-input-http/src/main/java/trible/histour/input/http/controller/AssistantApi.java, histour-input-http/src/main/java/trible/histour/input/http/controller/docs/AssistantApiDocs.java, histour-output-web/data/src/main/java/trible/histour/output/web/data/adapter/DataAdapter.java, histour-output-web/data/src/main/java/trible/histour/output/web/data/config/DataProperties.java, histour-output-web/data/src/main/resources/data-config/application-local.yml, histour-output-web/data/src/main/resources/data-config/application-prod.yml
=> feat: 챗봇 생성 API
